# Generated by Django 2.1.1 on 2018-10-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waittimes', '0003_ridecurrentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayWaitsPredicted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(db_column='Time')),
                ('predictedwait', models.IntegerField(db_column='PredictedWait')),
            ],
            options={
                'db_table': 'Ride_Waits_Today_Predicted',
                'managed': False,
            },
        ),
    ]
