# Generated by Django 2.1.1 on 2018-10-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waittimes', '0004_todaywaitspredicted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRideFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='UserId')),
                ('rideid', models.ForeignKey(db_column='RideId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='waittimes.Ride')),
            ],
            options={
                'db_table': 'User_Ride_Favorites',
            },
        ),
    ]
